version: '3'
services:

  web-app:
    container_name: exampleapp
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo-server
      - redis-server
  mongo-server:
    container_name: mymongodatabase
    image: mongo
    ports:
        - "27018:27017"
    depends_on:
      - redis-server

  redis-server:
    image: "redis:alpine"    
    ports: 
      - 6379:6379
    restart: always


      